// GENERATED by scripts/build-schema.mjs from rubric.txt - do not edit by hand.
export const SCHEMA_SQL = [
  "create table if not exists rubric_criteria (\n  id bigserial primary key,\n  role text not null check (role in ('PM','SPM')),\n  position int not null,\n  name text not null,\n  description text not null,\n  weight numeric not null,\n  unique (role, position)\n)",
  "create table if not exists candidates (\n  id uuid primary key default gen_random_uuid(),\n  created_at timestamptz not null default now(),\n  file_name text,\n  applied_role text not null check (applied_role in ('PM','SPM')),\n  personal jsonb not null default '{}'::jsonb,\n  cv_content text,\n  scores jsonb,\n  pm_score numeric,\n  spm_score numeric,\n  status text not null default 'new',\n  error text,\n  brief text,\n  email_type text,\n  email_subject text,\n  email_body text,\n  sent_at timestamptz,\n  draft_method text\n)",
  "alter table candidates add column if not exists draft_method text"
];

export const RUBRIC_ROWS = [
  {
    "role": "PM",
    "position": 1,
    "name": "Did the operational work firsthand",
    "description": "Has personally done the day-to-day work of an operations team (handled shipment documents, cleared customs holds, coordinated carriers, resolved delivery exceptions) as their own job, not as a consultant, interviewer or analyst watching others. A strong CV names specific documents, counterparties or volumes they handled (e.g. \"200+ shipments monthly\", \"coordinated with CHA and customs overnight\"). Weak: operations appear only as \"user research\", \"discovery calls\" or domain words in the summary.",
    "weight": 25
  },
  {
    "role": "PM",
    "position": 2,
    "name": "Built something unprompted that others adopted",
    "description": "Spotted a problem in their own team, built a fix nobody assigned (a tool, tracker, checklist or process), and gives evidence that other people chose to use it: a number of users, teams that adopted it, or a usage change. Weak: counts of features shipped, documents written or talks given, with no evidence anyone used them.",
    "weight": 25
  },
  {
    "role": "PM",
    "position": 3,
    "name": "Killed or failed, and wrote down why",
    "description": "Names at least one thing they stopped, lost or got wrong, states what the evidence showed, and says what changed as a result (e.g. \"killed 2 features after low adoption, moved the capacity to X, which got 3x usage\"). Weak: every bullet is a win, or failure appears only as an abstract lesson.",
    "weight": 20
  },
  {
    "role": "PM",
    "position": 4,
    "name": "No layer between them and the user",
    "description": "Worked directly with the people using the product or service and made the call themselves (sole owner of an area, no manager or product layer relaying requirements). A strong CV says who they dealt with directly. Weak: works through account managers, a larger PM team, or approval committees.",
    "weight": 15
  },
  {
    "role": "PM",
    "position": 5,
    "name": "Fixed it personally under time pressure",
    "description": "Describes a specific breakdown (a customs hold, a vendor format change, an outage, a failed migration) that they personally resolved against a clock, with the outcome stated. Weak: pressure described only as \"fast-paced environment\".",
    "weight": 15
  },
  {
    "role": "SPM",
    "position": 1,
    "name": "Did the operational work firsthand",
    "description": "Everything in the PM version, plus the operational experience directly shaped a product or system decision they later made (e.g. ops knowledge of port or customs systems led them to prioritise a specific integration). Weak: ops experience that sits unrelated to their product work.",
    "weight": 20
  },
  {
    "role": "SPM",
    "position": 2,
    "name": "Built something unprompted that others adopted",
    "description": "Started something without being asked that became part of the core product or the organisation's standard way of working, used beyond their own team. Weak: adoption limited to their own immediate team, or built only when assigned.",
    "weight": 15
  },
  {
    "role": "SPM",
    "position": 3,
    "name": "Killed or failed, and wrote down why",
    "description": "Made and owned a call with lasting consequences that turned out wrong or was reversed (a failed integration, a vendor choice, an architecture choice), and names the lasting change they made afterwards (a new standard, a process or a practice others now follow). Weak: only feature-level kills, or failures blamed on others.",
    "weight": 20
  },
  {
    "role": "SPM",
    "position": 4,
    "name": "No layer between them and the user",
    "description": "Was the final decision-maker for a product area or function with no senior PM, VP or committee reviewing their calls, for a sustained period, and says so explicitly. Weak: the title says Senior or Head of, but the CV shows roadmaps reviewed by a VP, long approval cycles, or shared ownership.",
    "weight": 30
  },
  {
    "role": "SPM",
    "position": 5,
    "name": "Fixed it personally under time pressure",
    "description": "Led resolution of a breakdown that affected customers or revenue (a migration, a major outage, a data-quality failure) and changed the system so it did not recur (e.g. an on-call rotation that cut P1 incidents by 40%). Weak: a one-off fix with no systemic change.",
    "weight": 15
  }
];
