// Regenerates lib/schema.js (used by the app to auto-create tables + seed the rubric)
// and db/schema.sql (manual SQL) from rubric.txt.
// Usage: node scripts/build-schema.mjs
import fs from 'fs';
import { parseRubric } from './rubricParse.js';

const rubric = parseRubric(fs.readFileSync('rubric.txt', 'utf8'));
for (const role of ['PM', 'SPM']) {
  const rows = rubric.filter((r) => r.role === role);
  const sum = rows.reduce((a, r) => a + r.weight, 0);
  if (rows.length < 4 || rows.length > 6 || sum !== 100) throw new Error(`${role}: ${rows.length} criteria, weights sum ${sum}`);
}

const SCHEMA = [
  `create table if not exists rubric_criteria (
  id bigserial primary key,
  role text not null check (role in ('PM','SPM')),
  position int not null,
  name text not null,
  description text not null,
  weight numeric not null,
  unique (role, position)
)`,
  `create table if not exists candidates (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  file_name text,
  applied_role text not null check (applied_role in ('PM','SPM')),
  personal jsonb not null default '{}'::jsonb,
  cv_content text,
  scores jsonb,
  pm_score numeric,
  spm_score numeric,
  status text not null default 'new',
  error text,
  brief text,
  email_type text,
  email_subject text,
  email_body text,
  sent_at timestamptz,
  draft_method text
)`,
  `alter table candidates add column if not exists draft_method text`,
];

fs.writeFileSync(
  'lib/schema.js',
  `// GENERATED by scripts/build-schema.mjs from rubric.txt - do not edit by hand.\n` +
    `export const SCHEMA_SQL = ${JSON.stringify(SCHEMA, null, 2)};\n\n` +
    `export const RUBRIC_ROWS = ${JSON.stringify(rubric, null, 2)};\n`
);

const qs = (s) => `'${String(s).replace(/'/g, "''")}'`;
const sqlText =
  `-- Kargo hiring dashboard schema. The app runs this automatically on first request;\n-- this file is for reference / manual setup.\n\n` +
  SCHEMA.map((s) => s + ';').join('\n\n') +
  `\n\n-- personal = name/email/phone (never sent to AI after extraction); cv_content = redacted CV text\n\ndelete from rubric_criteria;\n` +
  rubric.map((r) => `insert into rubric_criteria (role, position, name, description, weight) values (${qs(r.role)}, ${r.position}, ${qs(r.name)}, ${qs(r.description)}, ${r.weight});`).join('\n') +
  '\n';
fs.mkdirSync('db', { recursive: true });
fs.writeFileSync('db/schema.sql', sqlText);
console.log(`Wrote lib/schema.js and db/schema.sql with ${rubric.length} rubric rows`);
